---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
    events: pull_request pull_request_closed
  jobs:
  - name: Build
    type: builder
